version: '3.8'

services:
  # Database PostgreSQL untuk metadata Airflow
  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis sebagai broker untuk CeleryExecutor
  airflow-redis:
    image: redis:6.2
    container_name: airflow-redis
    ports:
      - "6379:6379"

  # Webserver Airflow
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://airflow-redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/home/budi-setiawan/Repository/data-engineering/dags
      - ./logs:/home/budi-setiawan/Repository/data-engineering/logs
      - ./plugins:/home/budi-setiawan/Repository/data-engineering/plugins
    ports:
      - "8080:8080"
    depends_on:
      - airflow-db
      - airflow-redis
    command: webserver

  # Scheduler Airflow
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://airflow-redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/home/budi-setiawan/Repository/data-engineering/dags
      - ./logs:/home/budi-setiawan/Repository/data-engineering/logs
      - ./plugins:/home/budi-setiawan/Repository/data-engineering/plugins
    depends_on:
      - airflow-db
      - airflow-redis
    command: scheduler

  # Worker Celery untuk menjalankan task
  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://airflow-redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/home/budi-setiawan/Repository/data-engineering/dags
      - ./logs:/home/budi-setiawan/Repository/data-engineering/logs
      - ./plugins:/home/budi-setiawan/Repository/data-engineering/plugins
    depends_on:
      - airflow-db
      - airflow-redis
    command: celery worker

volumes:
  postgres_data:
